---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: podinfo
  namespace: demo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: podinfod
      containers:
      - image: stefanprodan/podinfo:2.0.5
        name: podinfod
