---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: podinfo
  namespace: demo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: podinfod
      $setElementOrder/initContainers:
      - name: init
      containers:
      - image: stefanprodan/podinfo:4.0.1
        name: podinfod
      initContainers:
      - image: alpine:20200428
        name: init
